server:
  build: .
  ports:
    - "32000:5000"
  volumes:
    - ./src:/code/express-rest/src
  links:
    - mongo:mongo
mongo:
  image: mongo
  # Use this volume mount to get mongo to use a mapped volume
  # or comment out to get fresh db in container only.
  command: mongod --smallfiles --storageEngine=wiredTiger
  ports:
    - "27017:27017"
